title: Bitdribble
author:
  name: Andrei Radulescu-Banu
  email: "bitdribble@gmail.com"
description: > # this means to ignore newlines until "show_excerpts:"
  Bitdribble is a knowledge repository
  maintained by Andrei Radulescu-Banu.

show_excerpts: false # set to true to show excerpts on the homepage
permalink: pretty


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  #skin: classic
  skin: dark
  #skin: solarized-dark
  #skin: solarized

  # generate social links in footer
  social_links:
    twitter: bitdribble
    github:  bitdribble
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: andrei-radulescu-banu
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - title: "AI Topics"
    url: "#"
    children:
      - title: "Language Models"
        url: "/language_models"
      - title: "Self Driving Cars"
        url: "/self_driving_cars"
      - title: "Artificial Intelligence"
        url: "/artificial_intelligence"
      - title: "Computer Vision"
        url: "/computer_vision"
      - title: "Cognitive Science"
        url: "/cognitive_science"
  - title: "Tech Topics"
    url: "#"
    children:
      - title: "Market Trading"
        url: "/market_trading"
      - title: "Webdev"
        url: "/webdev"
      - title: "DevOps"
        url: "/devops"
      - title: "Biotech"
        url: "/biotech"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"

# Build settings
# theme: minima  # Removed - using Tailwind CSS instead

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-pdf-embed # Per example at https://github.com/MihajloNesic/minimal-mistakes-pdf-example/

future: true

# GitHub repository configuration
repository: bitdribble/bitdribble.github.io